apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../ephemeral-base

images:
  - name: registry.fullstack.pw/library/memorizer
    newTag: pr-will-be-replaced

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: "dev.memorizer.fullstack.pw"
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "dev.memorizer.fullstack.pw"
      - op: replace
        path: /spec/rules/0/host
        value: "dev.memorizer.fullstack.pw"
    target:
      kind: Ingress
      name: memorizer
