apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: writer
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: "endpoint"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "endpoint"
      secretName: writer-tls-ephemeral
  rules:
    - host: "endpoint"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: writer
                port:
                  number: 8080
